services:
  web:
    container_name: web-dev
    build:
      target: development
    volumes:
      - type: bind
        source: ../../web/src
        target: /app/src
    healthcheck:
      test: [ "CMD", "curl", "--fail", "http://localhost:3000/" ]
      interval: 5m
      start_period: 30s
      start_interval: 1s

  app:
    container_name: app-dev
    depends_on:
      - web
    build:
      target: development
    environment:
      ASPNETCORE_ENVIRONMENT: Development
    volumes:
      - type: bind
        source: ../../backend/src
        target: /app/src
      - type: volume
        source: app-bin
        target: /app/src/OnlineShop/bin
      - type: volume
        source: app-obj
        target: /app/src/OnlineShop/obj
volumes:
  app-bin:
  app-obj:
