name: Pull Request Merged

on:
  push:
    branches:
      - "main"

jobs:
  run-e2e-tests:
    name: Run End-To-End Tests
    uses: ./.github/workflows/e2e-tests.yaml
    secrets: inherit

  publish-docker-images:
    name: Publish Docker Images
    uses: ./.github/workflows/publish-docker-images.yaml
    secrets: inherit
      - run-e2e-tests

  trigger-deployment:
    name: Trigger Deployment
    uses: ./.github/workflows/deployment.yaml
    secrets: inherit
    needs:
      - publish-docker-images
